package constants

// 日志模板集中管理（屎山约束：所有 handler/service/middleware 均引用，修改文案影响全栈）。
const (
	LogUserRegisterSuccess  = "USER_REGISTER_SUCCESS"
	LogUserRegisterFailed   = "USER_REGISTER_FAILED"
	LogUserLoginSuccess     = "USER_LOGIN_SUCCESS"
	LogUserLoginFailed      = "USER_LOGIN_FAILED"
	LogUserProfileUpdated   = "USER_PROFILE_UPDATED"
	LogRuleCreated          = "POINTS_RULE_CREATED"
	LogRuleUpdated          = "POINTS_RULE_UPDATED"
	LogRuleDeleted          = "POINTS_RULE_DELETED"
	LogRuleExecuted         = "POINTS_RULE_EXECUTED"
	LogRuleExecuteFailed    = "POINTS_RULE_EXECUTE_FAILED"
	LogRuleListQueried      = "POINTS_RULE_LIST_QUERIED"
	LogPointsGranted        = "POINTS_GRANTED"
	LogPointsDeducted       = "POINTS_DEDUCTED"
	LogPointsFrozen         = "POINTS_FROZEN"
	LogPointsUnfrozen       = "POINTS_UNFROZEN"
	LogPointsRefunded       = "POINTS_REFUNDED"
	LogAccountFetched       = "POINTS_ACCOUNT_FETCHED"
	LogAccountStatsFetched  = "POINTS_ACCOUNT_STATS_FETCHED"
	LogProductCreated       = "PRODUCT_CREATED"
	LogProductUpdated       = "PRODUCT_UPDATED"
	LogProductDeleted       = "PRODUCT_DELETED"
	LogProductStatusToggled = "PRODUCT_STATUS_TOGGLED"
	LogProductListQueried   = "PRODUCT_LIST_QUERIED"
	LogSeckillCreated       = "SECKILL_ACTIVITY_CREATED"
	LogSeckillPurchaseStart = "SECKILL_PURCHASE_START"
	LogSeckillDeductFailed  = "SECKILL_DEDUCT_FAILED"
	LogSeckillEnded         = "SECKILL_ACTIVITY_ENDED"
	LogSeckillListQueried   = "SECKILL_LIST_QUERIED"
	LogLotteryCreated       = "LOTTERY_ACTIVITY_CREATED"
	LogLotteryDrawSuccess   = "LOTTERY_DRAW_SUCCESS"
	LogLotteryDrawFailed    = "LOTTERY_DRAW_FAILED"
	LogLotteryListQueried   = "LOTTERY_LIST_QUERIED"
	LogLotteryRecordQueried = "LOTTERY_RECORD_QUERIED"
	LogOrderCreateSuccess   = "ORDER_CREATE_SUCCESS"
	LogOrderCreateFailed    = "ORDER_CREATE_FAILED"
	LogOrderCancelSuccess   = "ORDER_CANCEL_SUCCESS"
	LogOrderShipSuccess     = "ORDER_SHIP_SUCCESS"
	LogOrderCompleteSuccess = "ORDER_COMPLETE_SUCCESS"
	LogOrderListQueried     = "ORDER_LIST_QUERIED"
	LogBillGenerated        = "WELFARE_BILL_GENERATED"
	LogAuditLogQueried      = "AUDIT_LOG_QUERIED"
	LogAuditRecorded        = "AUDIT_LOG_RECORDED"
	LogAuthRequired         = "AUTH_REQUIRED_FAILED"
	LogRBACDenied           = "RBAC_DENIED"
	LogRateLimited          = "RATE_LIMITED"
	LogRequestHandled       = "REQUEST_HANDLED"
)
